### ISSUE TITLE
Add fee

### ISSUE THREAD

**Issue by Kalypox** [pbrissaud/suivi-bourse-app#6]
Hi,

I think it could be good if we can add brokerage fees too.
For example when i bought 100 JPY stock, it cost 10€.

I try tomorrow too !

**Comment by Kalypox** [comment]
Hi,

I think it could be good if we can add brokerage fees too.
For example when i bought 100 JPY stock, it cost 10€.

I try tomorrow too !

**Comment by pbrissaud** [comment]
Hi,

Thanks for the contribution on my project ! It's an excellent idea, I'll add this feature soon

**Comment by pbrissaud** [comment]
This feature is added with release 2.0. Thanks for the submission !
