### ISSUE TITLE
Grafana not displaying data

### ISSUE THREAD

**Issue by junyanglee** [pbrissaud/suivi-bourse-app#7]
Hi, Grafana is not showing data after I did a docker-compose up, as shown below

![image](https://user-images.githubusercontent.com/60129533/106589858-73a33c00-6587-11eb-9be6-e264ca726d1d.png)

Do I need to specify the query to in relations to the data.json i used?

**Comment by pbrissaud** [comment]
Hi,

Can I see the data.json file that you used ?
