### ISSUE TITLE
Does not support partial shares; expects integers as quantity.

### ISSUE THREAD

**Issue by wooter** [pbrissaud/suivi-bourse-app#8]
**Describe the bug**
Trying partial shares, the app throws an error because the quantity field is an integer.

> An error has occured: 400: {"error":"partial write: field type conflict: input field \"quantity\" on measurement \"purchase\" is type float, already exists as type integer dropped=1"}

**To Reproduce**
Add a stock with float quantity:
`[
  {
    "name": "Bitcoin",
    "symbol": "BTC-EUR",
    "purchase": {
      "quantity": 0.02047884,
      "fee": 2,
      "cost_price": 985
    },
    "estate": {
      "quantity": 0 ,
      "received_dividend": 0
    }
  }
]`

**Expected behavior**
If the field would support floats, the float would be written to the db.

**Screenshots**

**Installation mode:** (choose one)
Standalone

**Comment by pbrissaud** [comment]
Hi,

Thanks for submitting this issue. I will correct in in the next release in few days. 

Best regards.
